default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: toy_app_dev

test:
  <<: *default
  database: toy_app_test

production:
  <<: *default
  database: toy_app_prod
