default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: toy_app_dev2

test:
  <<: *default
  database: toy_app_test2

production:
  <<: *default
  database: toy_app_prod2
