default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: toy_app_dev4

test:
  <<: *default
  database: toy_app_test4

production:
  <<: *default
  database: toy_app_prod4
