default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: toy_app_dev1

test:
  <<: *default
  database: toy_app_test1

production:
  <<: *default
  database: toy_app_prod1
